---
name: Jenna
surname: Melanson
position: "PhD Candidate"
pronouns: she/her
address: "Biodiversity Research Center, University of British Columbia"
phone: +1 360 200 9317
www: jmelanson98.github.io
email: "jenna.melanson@ubc.ca"
bluesky: jennamelanson.bsky.social
github: jmelanson98
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Location,
  "PhD in Zoology", "2020-", "University of British Columbia", "Vancouver, BC, Canada",
  "Bachelor of Science in Biological Engineering", "2016-2020", "Massachusetts Institute of Technology", "Cambridge, MA, USA"
) %>%
  detailed_entries(Degree, Year, Institution, Location)
```


# Publications

```{r}
library(dplyr)

# MAKE SURE WORKING DIRECTORY IS SET PROPERLY??
bibliography_entries("melanson.bib") %>%
  arrange(desc(year), issued)
```

# Talks

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```

# Posters

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```

# Research Experience

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```

# Honors/Awards

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```

# Teaching Experience

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```

# Mentorship

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```


# Service and Outreach

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```


# Additional Honors/Experience

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```
